server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://xmcc.jyqs.com:7001/eureka/
spring:
  application:
    name: microservice-dept
  druid:
    url: jdbc:mysql://localhost:3306/dept?useUnicode=true&characterEncoding=UTF-8&&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ccxm.microservicesapi.entity
bus:
  test: holee
